---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by raylanhong.
--- DateTime: 2023/8/7 10:14
---

local TestLuaRPCBase = {
    ClientRPC = {},     --S2C类RPC列表，类似UFUNCTION宏中的Client
}

local EPropertyClass = import("EPropertyClass")
TestLuaRPCBase.ClientRPC.ClientRPC_TestRPC = {
    -- 是否可靠RPC
    Reliable = true,
    -- 定义参数列表
    Params =
    {
        EPropertyClass.Str,
    }
}

function TestLuaRPCBase:ClientRPC_TestRPC(Str)
    print(Str)
end

return Class(nil, nil, TestLuaRPCBase)