---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by raylanhong.
--- DateTime: 2023/8/7 10:25
---

local TestLuaRPCC = {
    ClientRPC = {},     --S2C类RPC列表，类似UFUNCTION宏中的Client
}

local EPropertyClass = import("EPropertyClass")
TestLuaRPCC.ClientRPC.ClientRPC_TestRPCC = {
    -- 是否可靠RPC
    Reliable = true,
    -- 定义参数列表
    Params =
    {
        EPropertyClass.Str,
    }
}

function TestLuaRPCC:ClientRPC_TestRPCC(Str)
    print(Str)
end

local CTestLuaRPCB = require("TestLuaRPCB")
return Class(CTestLuaRPCB, nil, TestLuaRPCC)